language: php
php: 5.6
before_script:
    - find . -type f -name *.php | xargs -n1 php -l
script:
# Test veolia sud est $website=2
# ------------------------------
  - cd ${TRAVIS_BUILD_DIR}/tests;./RunVeoliaSudEst.sh
  - diff -B veolia_sudest_data/testVeoliaSudEst.txt veolia_sudest_data_src/testVeoliaSudEst.txt

# Test veoliaeau.fr $website=1
# ---------------------------
  # Erreur a corriger avant de reactiver les tests
  # - cd ${TRAVIS_BUILD_DIR}/tests;./RunVeoliaEau.sh 
  # - diff -B veolia_eau_data/testVeoliaEau.txt veolia_eau_data_src/testVeoliaEau.txt

# Test eau du grand lyon
#-----------------------
  - cd ${TRAVIS_BUILD_DIR}/tests;./RunEauGrandLyon.sh
  - diff -B veolia_Lyon_data/testVeoliaLyon.txt Veolia-Lyon/testVeoliaLyon.txt

after_success:
    # TBD
    - cd ${TRAVIS_BUILD_DIR}/tests
    - ls -latr
after_failure:
    - cd ${TRAVIS_BUILD_DIR}/tests
    - cat veolia_sudest_data/testVeoliaSudEst.txt
    - grep "displayConfig" veolia_sudest_data/testVeoliaSudEst.txt > results.txt
    - grep "displayConfig" veolia_sudest_data_src/testVeoliaSudEst.txt > base.txt
    - diff  base.txt results.txt
    - ls -latr
#deploy:
#     provider: releases
#     api_key:
#         secure: $GH_TOKEN
#     file:
#         - veolia_sudest_data/testVeoliaSudEst.txt
#     skip_cleanup: true
#     on:
#       repo: rjullien/plugin-veolia_eau
#       branche: master